### ISSUE TITLE
svd2rust crashes with some SVDs

### ISSUE THREAD

**Issue by maximevince** [rust-embedded/svd2rust#145]
When trying
"svd2rust -i BlueNRG1.svd"
it crashes in: thread 'main' panicked at 'svd-parser-0.5.2/src/lib.rs:411 tree.get_child("bitWidth")', src/libcore/option.rs:819:4

BlueNRG1.svd can be found as part of "STMicroelectronics BlueNRG-1 Series Device Support" here: https://www.keil.com/dd2/pack/

**Comment by Detegr** [comment]
I'm having similar issue with SVD's in http://www.st.com/resource/en/svd/stm32l0_svd.zip
```
$ svd2rust -i STM32L0x3.svd
tree.get_child("mpuPresent")', /checkout/src/libcore/option.rs:839:4
```

**Comment by pftbest** [comment]
svd parser doesn't have a proper error handling, so it just panics when SVD file is incorrect. See https://github.com/japaric/svd2rust/issues/136

**Comment by japaric** [comment]
@maximevince Hmm, that may be a bug in the SVD parser since the [SVD spec](https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_Format_pg.html) says that `<bitWidth>` is [optional](https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html). in bit ranges.

@Detegr `<mpuPresent>` is a mandatory subfield of [`<cpu>`](https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_cpu.html). Your SVD file doesn't adhere to the standard so you'll have to fix it.

**Comment by Emilgardis** [comment]
BlueNRG1.svd has `derivedFrom` attributes on `MFT1_TIMER_B`, which is why svd-parser crashes. 
Related japaric/svd#21

**Comment by robinvalk** [comment]
I'm having the same issue with the BlueNRG2.svd file. Is there anything I can edit manually to get this file parsed?

**Comment by robinvalk** [comment]
Allright, I manually mapped all the bitWidth fields and fixed some issues in the SVD itself. File is now parsed.

I see that the derivedFrom attribute parsing is not yet implemented on the Field element. When I find the time I might create a PR to implement this.

**Comment by robinvalk** [comment]
Unfortunately, I'm not going to find the time...

**Comment by burrbull** [comment]
Should be fixed. Reopen if it is not.
