### ISSUE TITLE
svd2rust bors still broken...

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/svd2rust#247]
I was looking around a little bit in the configuration, compared to various other projects and tried to refresh some settings in the hope to revive it. A few things are still odd but I didn't want to touch them, maybe someone (especially @japaric) could comment:

* https://github.com/rust-embedded/svd2rust/settings/hooks still contains broken references to @japarics homu and appveyor
* https://github.com/rust-embedded/svd2rust/settings/installations still shows an outdated Travis CI service which used to be uses with @japaric's credentials (Probably can be turned off now since toggling the integration in Travis-CI made it show up under webhooks)
* https://raw.githubusercontent.com/rust-embedded/svd2rust/master/.github/bors.toml still mentions  "continuous-integration/appveyor/branch" in the status configuration which other (working) repos do not.

@rust-embedded/ops 
@rust-embedded/resources Other ideas? We should really get this sorted out rather sooner than later...

**Comment by japaric** [comment]
> https://github.com/rust-embedded/svd2rust/settings/hooks still contains broken references to @japarics homu and appveyor

The homu stuff doesn't matter since we are using bors (I have deleted that outdated webhook). The appveyor stuff should be green otherwise the Windows CI is not working.

The last appveyor webhook response says

> {"message":"Push request and project repositories do not match."}

Which probably means the webhook broke after moving the repository. Either appveyor doesn't transparently handle GH repo transfers or, maybe, rust-embedded doesn't have an appveyor account (?).

> https://github.com/rust-embedded/svd2rust/settings/installations still shows an outdated Travis CI service which used to be uses with @japaric's credentials

Hmm, I wonder why that one shows as *not* active. The other repos have it active.

> https://raw.githubusercontent.com/rust-embedded/svd2rust/master/.github/bors.toml still mentions "continuous-integration/appveyor/branch" in the status configuration which other (working) repos do not.

That's supposed to be there. We run CI on windows, or rather we are supposed to: the last appveyor build has date from 6 months ago which matches the date of [last release](https://github.com/rust-embedded/svd2rust/releases/tag/v0.13.1) (which provides Windows binaries)

I would suggest replacing the appveyor stuff with Travis CI now that it provides Windows support. That way bors only has to monitor the Travis status.

**Comment by therealprof** [comment]
I just received confirmation that appveyor is now authorized but somehow appveyor doesn't should that in it's dashboard and I also have no idea how to activate it in GH for the svd2rust repository.

**Comment by nastevens** [comment]
I'd second looking at Travis instead: there are a lot of limitations with AppVeyor: https://github.com/crate-ci/meta/issues/25

**Comment by therealprof** [comment]
Not a problem at the moment anymore.
