### ISSUE TITLE
Vector type isn't repr(C)

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/svd2rust#755]
Someone asked me:

> Why isn't the Vector union in the PAC repr(C)

and I didn't know the answer. As we rely on the alignment and representation, it feels like it should be?

**Comment by adamgreig** [comment]
Yep, I believe it should be. Since both the types inside the union have the same repr as the corresponding C types and the same size and alignment as each other (on our targets anyway), there's very little scope for rustc to do anything wrong with the default union repr, but nevertheless it should be. I've opened #756 to fix.

**Comment by burrbull** [comment]
Fixed by #756
