### ISSUE TITLE
Current `master` branch does not build with `--no-default-features`

### ISSUE THREAD

**Issue by jessebraham** [rust-embedded/svd2rust#875]
I've updated the workflow in my fork to include this option, failing run can be seen here:  
https://github.com/jessebraham/svd2rust/actions/runs/11481198244

Enabling the `yaml` feature also does not resolve this:
https://github.com/jessebraham/svd2rust/actions/runs/11481238404

**Comment by jannic** [comment]
This is caused by https://github.com/rust-embedded/svd2rust/pull/856/files introducing a settings.yaml file that is parsed using serde_yaml, which is currently an optional dependency.

The easiest solution would be to make that dependency mandatory. Is there anything wrong with that?

The dependency was made optional in https://github.com/rust-embedded/svd2rust/pull/619. That doesn't look like a strict requirement, more like an optimization.

The alternative would be to disable the yaml config file if the dependency is disabled. But IMHO that would be unnecessarily confusing.

**Comment by Emilgardis** [comment]
I think it would make sense to make the library work without `serde_yaml`, there's nothing in the functionality of svd2rust as a library that strictly requires it.
